### ISSUE TITLE
More template filters

### ISSUE THREAD

**Issue by toabi** [couchbase/service-broker#48]
I wanted to convert some parameters to lowercase and didn't find a way to do it in a template.

Maybe it would be easy and useful to integrate http://masterminds.github.io/sprig/ - looking at the functions there some other use cases come to my mind.

**Comment by spjmurray** [comment]
From a testing perspective, I'm not going to throw the whole lot in :smiley_cat: besides, the service broker already supports TLS in a better way than sprig, so I want to be selective and do some proper engineering.  But good inclusion for the next release.  Are we just talking basic string manipulation e.g. upper/lower or are there other things on your list?

**Comment by toabi** [comment]
In the meantime I didn't stumble upon anything. Most times I'd probably use "upper"/"lower"/"title" to generate Labels/Hostnames/Things™ from user-provided parameters. There's really no need for something gigantic than sprig.
