### ISSUE TITLE
Advanced Templating (loops)

### ISSUE THREAD

**Issue by toabi** [couchbase/service-broker#52]
I would need to loop over some list of things in a configmap. Maybe I'm just holding go templates wrong?

I tried something like

```
      data:
        test.conf: '{{range (list 0 1 2) }}
                      upstream rs0-{{ . }} { server "dings-rs0-{{ . }}" }
                    {{end}}'
```

Is something like this even possible?

**Comment by spjmurray** [comment]
No :wink:  The "range" and other branch style template nodes always return concatenated strings, which doesn't preserve _structure_, remember the broker likes typed data, not template strings.

Now what we could do is something like:

```yaml
key: '{{ snippetArray "snippet-name" (list 0 1 2) }}'
```

Then define the snippet as:

```yaml
templates:
- name: snippet-name
  template: '{{ printf "something-%d" }}
```

and that should yield:
  
```json
[
  "something-0",
  "something-1",
  "something-2"
]
```

The core functionality would be, for each member in the list set _dot_ to be that (could be a scalar, object, a nested array), then render the template.  Each result should be then unmarshalled and appended to an `[]interface{}`.  Or something of that ilk.

All conjecture at the moment as you're disappearing quickly into uncharted waters!
